// 石油行业 + 日常高频词库（扩充版）
// 结构: { word, phonetic, pos, meaning, example, exampleCn, tag }
// tag: 'oil' 石油专业 | 'daily' 日常交流 | 'driving' 开车场景 | 'industry' 行业术语
const WORD_BANK = [
  // ===== 石油勘探 (Exploration) =====
  { word: "petroleum", phonetic: "/pəˈtrəʊliəm/", pos: "n.", meaning: "石油", example: "Petroleum is formed from ancient organisms.", exampleCn: "石油由古代生物形成。", tag: "oil" },
  { word: "exploration", phonetic: "/ˌekspləˈreɪʃn/", pos: "n.", meaning: "勘探", example: "Exploration drilling requires large investment.", exampleCn: "勘探钻井需要大量投资。", tag: "oil" },
  { word: "seismic survey", phonetic: "/ˈsaɪzmɪk ˈsɜːveɪ/", pos: "n.", meaning: "地震勘探", example: "A 3D seismic survey mapped the reservoir.", exampleCn: "三维地震勘探绘制了储层图。", tag: "oil" },
  { word: "geology", phonetic: "/dʒiˈɒlədʒi/", pos: "n.", meaning: "地质学", example: "Reservoir geology determines production.", exampleCn: "储层地质决定产能。", tag: "oil" },
  { word: "stratigraphy", phonetic: "/strəˈtɪɡrəfi/", pos: "n.", meaning: "地层学", example: "Stratigraphy reveals the layering of rock.", exampleCn: "地层学揭示岩层结构。", tag: "oil" },
  { word: "sedimentary", phonetic: "/ˌsedɪˈmentri/", pos: "adj.", meaning: "沉积的", example: "Most oil is found in sedimentary rock.", exampleCn: "大多数石油产于沉积岩。", tag: "oil" },
  { word: "sandstone", phonetic: "/ˈsændstəʊn/", pos: "n.", meaning: "砂岩", example: "Sandstone is a common reservoir rock.", exampleCn: "砂岩是常见储层岩。", tag: "oil" },
  { word: "carbonate", phonetic: "/ˈkɑːbəneɪt/", pos: "n.", meaning: "碳酸盐岩", example: "Carbonate reservoirs are often fractured.", exampleCn: "碳酸盐岩储层常含裂缝。", tag: "oil" },
  { word: "shale", phonetic: "/ʃeɪl/", pos: "n.", meaning: "页岩", example: "Shale gas is a major unconventional resource.", exampleCn: "页岩气是重要非常规资源。", tag: "oil" },
  { word: "cap rock", phonetic: "/kæp rɒk/", pos: "n.", meaning: "盖岩；盖层", example: "Cap rock seals the hydrocarbon trap.", exampleCn: "盖层封闭油气圈闭。", tag: "oil" },
  { word: "trap", phonetic: "/træp/", pos: "n.", meaning: "圈闭", example: "A structural trap holds the oil in place.", exampleCn: "构造圈闭将油封闭于地下。", tag: "oil" },
  { word: "anticline", phonetic: "/ˈæntɪklaɪn/", pos: "n.", meaning: "背斜", example: "Many oil fields are found in anticlines.", exampleCn: "许多油田发现于背斜构造。", tag: "oil" },
  { word: "fault", phonetic: "/fɔːlt/", pos: "n.", meaning: "断层", example: "The fault cuts across the reservoir.", exampleCn: "断层切穿储层。", tag: "oil" },
  { word: "reservoir", phonetic: "/ˈrezəvwɑː/", pos: "n.", meaning: "储层；油藏", example: "The reservoir holds significant oil reserves.", exampleCn: "该储层蕴藏大量石油储量。", tag: "oil" },
  { word: "porosity", phonetic: "/pɔːˈrɒsəti/", pos: "n.", meaning: "孔隙度", example: "Porosity measures void space in rock.", exampleCn: "孔隙度衡量岩石中的空隙空间。", tag: "oil" },
  { word: "permeability", phonetic: "/ˌpɜːmiəˈbɪləti/", pos: "n.", meaning: "渗透率", example: "High permeability allows fluid to flow.", exampleCn: "高渗透率使流体易于流动。", tag: "oil" },
  { word: "hydrocarbon", phonetic: "/ˌhaɪdrəˈkɑːbən/", pos: "n.", meaning: "碳氢化合物；烃", example: "Natural gas is a gaseous hydrocarbon.", exampleCn: "天然气是一种气态烃。", tag: "oil" },
  { word: "crude oil", phonetic: "/kruːd ɔɪl/", pos: "n.", meaning: "原油", example: "Crude oil is refined into many products.", exampleCn: "原油被加工成多种产品。", tag: "oil" },
  { word: "natural gas", phonetic: "/ˈnætʃrəl ɡæs/", pos: "n.", meaning: "天然气", example: "Natural gas burns cleanly.", exampleCn: "天然气燃烧更清洁。", tag: "oil" },
  { word: "condensate", phonetic: "/kənˈdenseɪt/", pos: "n.", meaning: "凝析油；凝析气", example: "Condensate is a light liquid hydrocarbon.", exampleCn: "凝析油是轻质液态烃。", tag: "oil" },
  { word: "methane", phonetic: "/ˈmiːθeɪn/", pos: "n.", meaning: "甲烷", example: "Methane is the main component of natural gas.", exampleCn: "甲烷是天然气的主要成分。", tag: "oil" },

  // ===== 钻井 (Drilling) =====
  { word: "drilling", phonetic: "/ˈdrɪlɪŋ/", pos: "n.", meaning: "钻井；钻探", example: "Offshore drilling requires specialized equipment.", exampleCn: "海上钻井需要专业设备。", tag: "oil" },
  { word: "rig", phonetic: "/rɪɡ/", pos: "n.", meaning: "钻机；钻井平台", example: "The rig drilled to a depth of 5,000 meters.", exampleCn: "钻机钻到了 5000 米深度。", tag: "oil" },
  { word: "derrick", phonetic: "/ˈderɪk/", pos: "n.", meaning: "井架", example: "The derrick stands 40 meters tall.", exampleCn: "井架高 40 米。", tag: "oil" },
  { word: "drill bit", phonetic: "/drɪl bɪt/", pos: "n.", meaning: "钻头", example: "The drill bit wears out in hard rock.", exampleCn: "钻头在硬岩层中磨损很快。", tag: "oil" },
  { word: "drill string", phonetic: "/drɪl strɪŋ/", pos: "n.", meaning: "钻柱", example: "The drill string transmits rotation to the bit.", exampleCn: "钻柱把扭矩传给钻头。", tag: "oil" },
  { word: "drill pipe", phonetic: "/drɪl paɪp/", pos: "n.", meaning: "钻杆", example: "Each drill pipe is about ten meters long.", exampleCn: "每根钻杆约十米长。", tag: "oil" },
  { word: "drill collar", phonetic: "/drɪl ˈkɒlə/", pos: "n.", meaning: "钻铤", example: "Drill collars provide weight on the bit.", exampleCn: "钻铤为钻头提供钻压。", tag: "oil" },
  { word: "kelly", phonetic: "/ˈkeli/", pos: "n.", meaning: "方钻杆", example: "The kelly connects the rotary table to the string.", exampleCn: "方钻杆连接转盘与钻柱。", tag: "oil" },
  { word: "top drive", phonetic: "/tɒp draɪv/", pos: "n.", meaning: "顶驱", example: "Top drives improve drilling efficiency.", exampleCn: "顶驱提高了钻井效率。", tag: "oil" },
  { word: "rotary table", phonetic: "/ˈrəʊtəri ˈteɪbl/", pos: "n.", meaning: "转盘", example: "The rotary table turns the drill string.", exampleCn: "转盘带动钻柱旋转。", tag: "oil" },
  { word: "mud", phonetic: "/mʌd/", pos: "n.", meaning: "钻井液；泥浆", example: "Drilling mud cools and lubricates the bit.", exampleCn: "钻井液冷却并润滑钻头。", tag: "oil" },
  { word: "mud pit", phonetic: "/mʌd pɪt/", pos: "n.", meaning: "泥浆池", example: "Mud is circulated through the mud pit.", exampleCn: "泥浆通过泥浆池循环。", tag: "oil" },
  { word: "shale shaker", phonetic: "/ʃeɪl ˈʃeɪkə/", pos: "n.", meaning: "振动筛", example: "The shale shaker removes cuttings from mud.", exampleCn: "振动筛清除泥浆中的岩屑。", tag: "oil" },
  { word: "weight on bit", phonetic: "/weɪt ɒn bɪt/", pos: "n.", meaning: "钻压（WOB）", example: "High WOB can damage the bit.", exampleCn: "高钻压可能损坏钻头。", tag: "oil" },
  { word: "rotary speed", phonetic: "/ˈrəʊtəri spiːd/", pos: "n.", meaning: "转盘转速（rpm）", example: "Optimal rotary speed improves ROP.", exampleCn: "最佳转速可提高机械钻速。", tag: "oil" },
  { word: "rate of penetration", phonetic: "/reɪt əv ˌpenɪˈtreɪʃn/", pos: "n.", meaning: "机械钻速（ROP）", example: "ROP depends on bit type and formation.", exampleCn: "机械钻速取决于钻头类型和地层。", tag: "oil" },
  { word: "directional drilling", phonetic: "/daɪˈrekʃənl ˈdrɪlɪŋ/", pos: "n.", meaning: "定向钻井", example: "Directional drilling reaches horizontal targets.", exampleCn: "定向钻井可钻达水平目标。", tag: "oil" },
  { word: "horizontal well", phonetic: "/ˌhɒrɪˈzɒntl wel/", pos: "n.", meaning: "水平井", example: "Horizontal wells boost shale production.", exampleCn: "水平井提高页岩产量。", tag: "oil" },
  { word: "sidetrack", phonetic: "/ˈsaɪdtræk/", pos: "n./v.", meaning: "侧钻；偏离原井眼", example: "We sidetracked to avoid the fish.", exampleCn: "我们侧钻避开落鱼。", tag: "oil" },
  { word: "fish", phonetic: "/fɪʃ/", pos: "n.", meaning: "落鱼（井下落物）", example: "We need to recover the fish from the hole.", exampleCn: "我们需要从井内打捞落鱼。", tag: "oil" },
  { word: "stuck pipe", phonetic: "/stʌk paɪp/", pos: "n.", meaning: "卡钻", example: "Stuck pipe requires immediate action.", exampleCn: "卡钻需立即处理。", tag: "oil" },
  { word: "lost circulation", phonetic: "/lɒst ˌsɜːkjəˈleɪʃn/", pos: "n.", meaning: "井漏", example: "Lost circulation can be a serious problem.", exampleCn: "井漏可能是严重问题。", tag: "oil" },
  { word: "kick", phonetic: "/kɪk/", pos: "n.", meaning: "井涌", example: "A kick must be controlled immediately.", exampleCn: "井涌必须立即控制。", tag: "oil" },
  { word: "blowout", phonetic: "/ˈbləʊaʊt/", pos: "n.", meaning: "井喷", example: "A blowout preventer is a critical safety device.", exampleCn: "防喷器是关键的安仼装置。", tag: "oil" },
  { word: "BOP", phonetic: "/biː əʊ piː/", pos: "n.", meaning: "防喷器（Blowout Preventer）", example: "The BOP was tested before drilling.", exampleCn: "钻井前对防喷器进行了试压。", tag: "oil" },
  { word: "well control", phonetic: "/wel kənˈtrəʊl/", pos: "n.", meaning: "井控", example: "Well control is critical for safety.", exampleCn: "井控对安全至关重要。", tag: "oil" },
  { word: "well kill", phonetic: "/wel kɪl/", pos: "n./v.", meaning: "压井", example: "We need to kill the well first.", exampleCn: "我们需要先压井。", tag: "oil" },
  { word: "shut in", phonetic: "/ʃʌt ɪn/", pos: "v.", meaning: "关井", example: "We will shut in the well for a workover.", exampleCn: "我们将关井进行修井作业。", tag: "oil" },
  { word: "wellhead", phonetic: "/ˈwelhed/", pos: "n.", meaning: "井口", example: "Pressure at the wellhead is monitored.", exampleCn: "井口压力被持续监测。", tag: "oil" },
  { word: "Christmas tree", phonetic: "/ˈkrɪsməs triː/", pos: "n.", meaning: "采油树；井口装置", example: "The Christmas tree controls flow at the wellhead.", exampleCn: "采油树控制井口产出。", tag: "oil" },
  { word: "choke", phonetic: "/tʃəʊk/", pos: "n.", meaning: "节流阀；油嘴", example: "Open the choke to increase flow.", exampleCn: "打开油嘴提高产量。", tag: "oil" },
  { word: "flow rate", phonetic: "/fləʊ reɪt/", pos: "n.", meaning: "流量；产量", example: "Flow rate has increased to 1000 bbl/d.", exampleCn: "产量提升到 1000 桶/日。", tag: "oil" },
  { word: "barrel", phonetic: "/ˈbærəl/", pos: "n.", meaning: "桶（石油计量单位）", example: "One barrel equals 42 US gallons.", exampleCn: "一桶等于 42 美制加仑。", tag: "oil" },
  { word: "bbl", phonetic: "/biː biː el/", pos: "n.", meaning: "桶（缩写）", example: "Production is 5000 bbl per day.", exampleCn: "产量为 5000 桶/日。", tag: "oil" },
  { word: "psi", phonetic: "/piː es ˈaɪ/", pos: "n.", meaning: "磅/平方英寸（压力单位）", example: "The pressure reached 3000 psi.", exampleCn: "压力达到 3000 psi。", tag: "oil" },
  { word: "offshore", phonetic: "/ˌɒfˈʃɔː/", pos: "adj.", meaning: "海上的", example: "Offshore platforms are expensive to build.", exampleCn: "海上钻井平台造价高昂。", tag: "oil" },
  { word: "onshore", phonetic: "/ˈɒnʃɔː/", pos: "adj.", meaning: "陆上的", example: "Onshore wells are easier to access.", exampleCn: "陆上井更容易到达。", tag: "oil" },

  // ===== 完井与井下作业 (Completion & Workover) =====
  { word: "casing", phonetic: "/ˈkeɪsɪŋ/", pos: "n.", meaning: "套管", example: "Steel casing protects the well from collapse.", exampleCn: "钢套管防止井壁坍塌。", tag: "oil" },
  { word: "casing string", phonetic: "/ˈkeɪsɪŋ strɪŋ/", pos: "n.", meaning: "套管柱", example: "Casing strings are cemented in place.", exampleCn: "套管柱被固井固定。", tag: "oil" },
  { word: "cementing", phonetic: "/sɪˈmentɪŋ/", pos: "n.", meaning: "固井", example: "Cementing seals the space behind the casing.", exampleCn: "固井封固套管外的环空。", tag: "oil" },
  { word: "cement", phonetic: "/sɪˈment/", pos: "n.", meaning: "水泥；固井水泥", example: "Cement is pumped down the casing.", exampleCn: "水泥被泵入套管内。", tag: "oil" },
  { word: "tubing", phonetic: "/ˈtjuːbɪŋ/", pos: "n.", meaning: "油管", example: "Production tubing carries oil to the surface.", exampleCn: "生产油管把石油输送到地面。", tag: "oil" },
  { word: "completion", phonetic: "/kəmˈpliːʃn/", pos: "n.", meaning: "完井", example: "Well completion prepares the well for production.", exampleCn: "完井使油井具备生产条件。", tag: "oil" },
  { word: "perforation", phonetic: "/ˌpɜːfəˈreɪʃn/", pos: "n.", meaning: "射孔", example: "Perforation connects the wellbore to the reservoir.", exampleCn: "射孔连通了井筒与储层。", tag: "oil" },
  { word: "perforating gun", phonetic: "/ˈpɜːfəreɪtɪŋ ɡʌn/", pos: "n.", meaning: "射孔枪", example: "The perforating gun is run on wireline.", exampleCn: "射孔枪用电缆下入。", tag: "oil" },
  { word: "liner", phonetic: "/ˈlaɪnə/", pos: "n.", meaning: "尾管；衬管", example: "A liner is hung from a liner hanger.", exampleCn: "尾管悬挂在悬挂器上。", tag: "oil" },
  { word: "packer", phonetic: "/ˈpækə/", pos: "n.", meaning: "封隔器", example: "A packer isolates the production zone.", exampleCn: "封隔器隔离生产层段。", tag: "oil" },
  { word: "frac", phonetic: "/fræk/", pos: "n.", meaning: "压裂（fracturing 缩写）", example: "The frac job used 2 million gallons of fluid.", exampleCn: "压裂作业使用了 200 万加仑液体。", tag: "oil" },
  { word: "fracturing", phonetic: "/ˈfræktʃərɪŋ/", pos: "n.", meaning: "压裂；破裂", example: "Hydraulic fracturing boosts well productivity.", exampleCn: "水力压裂提高了油井产能。", tag: "oil" },
  { word: "hydraulic fracturing", phonetic: "/haɪˈdrɒlɪk ˈfræktʃərɪŋ/", pos: "n.", meaning: "水力压裂", example: "Hydraulic fracturing enables shale production.", exampleCn: "水力压裂使页岩气开发成为可能。", tag: "oil" },
  { word: "acidizing", phonetic: "/ˈæsɪdaɪzɪŋ/", pos: "n.", meaning: "酸化", example: "Matrix acidizing removes formation damage.", exampleCn: "基质酸化解除地层伤害。", tag: "oil" },
  { word: "proppant", phonetic: "/ˈprɒpənt/", pos: "n.", meaning: "支撑剂", example: "Sand is the most common proppant.", exampleCn: "石英砂是最常见的支撑剂。", tag: "oil" },
  { word: "workover", phonetic: "/ˈwɜːkəʊvə/", pos: "n.", meaning: "修井", example: "A workover rig repairs damaged wells.", exampleCn: "修井机维修受损的油井。", tag: "oil" },
  { word: "well intervention", phonetic: "/wel ˌɪntəˈvenʃn/", pos: "n.", meaning: "井下作业；修井", example: "Well intervention restores production.", exampleCn: "修井作业恢复产量。", tag: "oil" },
  { word: "coiled tubing", phonetic: "/kɔɪld ˈtjuːbɪŋ/", pos: "n.", meaning: "连续油管", example: "Coiled tubing is used in many interventions.", exampleCn: "连续油管用于多种井下作业。", tag: "oil" },
  { word: "wireline", phonetic: "/ˈwaɪəlaɪn/", pos: "n.", meaning: "电缆", example: "Wireline logs are run in the well.", exampleCn: "电缆测井在井内进行。", tag: "oil" },
  { word: "slickline", phonetic: "/ˈslɪklaɪn/", pos: "n.", meaning: "钢丝", example: "Slickline is used for simple interventions.", exampleCn: "钢丝用于简单井下作业。", tag: "oil" },

  // ===== 采油与生产 (Production) =====
  { word: "production", phonetic: "/prəˈdʌkʃn/", pos: "n.", meaning: "生产；产量", example: "Daily oil production reached 10,000 barrels.", exampleCn: "日产量达到了一万桶。", tag: "oil" },
  { word: "artificial lift", phonetic: "/ˌɑːtɪˈfɪʃl lɪft/", pos: "n.", meaning: "人工举升", example: "Artificial lift is needed when pressure declines.", exampleCn: "压力下降时需要人工举升。", tag: "oil" },
  { word: "pumpjack", phonetic: "/ˈpʌmpdʒæk/", pos: "n.", meaning: "游梁式抽油机", example: "The pumpjack nods up and down.", exampleCn: "抽油机上下往复运动。", tag: "oil" },
  { word: "ESP", phonetic: "/iː es piː/", pos: "n.", meaning: "电潜泵", example: "The ESP is set at 2,000 meters.", exampleCn: "电潜泵下入 2000 米。", tag: "oil" },
  { word: "gas lift", phonetic: "/ɡæs lɪft/", pos: "n.", meaning: "气举", example: "Gas lift uses injected gas to lift liquids.", exampleCn: "气举用注入气体举升液体。", tag: "oil" },
  { word: "water injection", phonetic: "/ˈwɔːtər ɪnˌdʒekʃn/", pos: "n.", meaning: "注水", example: "Water injection maintains reservoir pressure.", exampleCn: "注水保持地层压力。", tag: "oil" },
  { word: "EOR", phonetic: "/iː əʊ ɑː/", pos: "n.", meaning: "提高采收率（Enhanced Oil Recovery）", example: "EOR can increase recovery to over 50%.", exampleCn: "提高采收率技术可使采收率超过 50%。", tag: "oil" },
  { word: "water cut", phonetic: "/ˈwɔːtə kʌt/", pos: "n.", meaning: "含水率", example: "Water cut has reached 80%.", exampleCn: "含水率已达 80%。", tag: "oil" },
  { word: "GOR", phonetic: "/dʒiː əʊ ɑː/", pos: "n.", meaning: "气油比（Gas-Oil Ratio）", example: "High GOR indicates gas breakthrough.", exampleCn: "高气油比预示气窜。", tag: "oil" },
  { word: "recovery factor", phonetic: "/rɪˈkʌvəri ˈfæktə/", pos: "n.", meaning: "采收率", example: "Recovery factor varies by reservoir type.", exampleCn: "采收率随储层类型变化。", tag: "oil" },
  { word: "produced water", phonetic: "/prəˈdjuːst ˈwɔːtə/", pos: "n.", meaning: "采出水", example: "Produced water must be treated.", exampleCn: "采出水需要处理。", tag: "oil" },

  // ===== 储运与炼化 (Storage, Transport & Refining) =====
  { word: "pipeline", phonetic: "/ˈpaɪplaɪn/", pos: "n.", meaning: "管线；管道", example: "The pipeline transports crude oil across the region.", exampleCn: "该管道跨区域输送原油。", tag: "oil" },
  { word: "gathering station", phonetic: "/ˈɡæðərɪŋ ˈsteɪʃn/", pos: "n.", meaning: "集输站", example: "The gathering station collects flow from multiple wells.", exampleCn: "集输站汇集多井产出。", tag: "oil" },
  { word: "storage tank", phonetic: "/ˈstɔːrɪdʒ tæŋk/", pos: "n.", meaning: "储罐", example: "Floating roof tanks reduce evaporation loss.", exampleCn: "浮顶罐减少蒸发损失。", tag: "oil" },
  { word: "LNG", phonetic: "/el en dʒiː/", pos: "n.", meaning: "液化天然气", example: "LNG must be kept below minus 162 Celsius.", exampleCn: "LNG 需保持在零下 162 度以下。", tag: "oil" },
  { word: "LPG", phonetic: "/el piː dʒiː/", pos: "n.", meaning: "液化石油气", example: "LPG is used for cooking and heating.", exampleCn: "LPG 用于炊事和取暖。", tag: "oil" },
  { word: "pigging", phonetic: "/ˈpɪɡɪŋ/", pos: "n.", meaning: "清管作业", example: "Regular pigging keeps the pipeline clean.", exampleCn: "定期清管保持管道清洁。", tag: "oil" },
  { word: "refinery", phonetic: "/rɪˈfaɪnəri/", pos: "n.", meaning: "炼油厂", example: "The refinery processes crude into fuel.", exampleCn: "炼油厂把原油加工成燃料。", tag: "oil" },
  { word: "distillation", phonetic: "/ˌdɪstɪˈleɪʃn/", pos: "n.", meaning: "蒸馏", example: "Crude oil is separated by distillation.", exampleCn: "原油通过蒸馏分离。", tag: "oil" },
  { word: "cracking", phonetic: "/ˈkrækɪŋ/", pos: "n.", meaning: "裂化", example: "Catalytic cracking breaks heavy molecules.", exampleCn: "催化裂化分解重组分分子。", tag: "oil" },
  { word: "reforming", phonetic: "/rɪˈfɔːmɪŋ/", pos: "n.", meaning: "重整", example: "Reforming improves gasoline octane.", exampleCn: "重整提高汽油辛烷值。", tag: "oil" },
  { word: "desulfurization", phonetic: "/diːˌsʌlfəraɪˈzeɪʃn/", pos: "n.", meaning: "脱硫", example: "Desulfurization removes H2S from gas.", exampleCn: "脱硫去除天然气中的硫化氢。", tag: "oil" },
  { word: "separator", phonetic: "/ˈsepəreɪtə/", pos: "n.", meaning: "分离器", example: "The separator splits gas, oil, and water.", exampleCn: "分离器把气、油、水分开。", tag: "oil" },
  { word: "gasoline", phonetic: "/ˈɡæsəliːn/", pos: "n.", meaning: "汽油", example: "Gasoline demand peaks in summer.", exampleCn: "汽油需求在夏季达峰。", tag: "oil" },
  { word: "diesel", phonetic: "/ˈdiːzəl/", pos: "n.", meaning: "柴油", example: "Diesel engines are highly efficient.", exampleCn: "柴油机效率很高。", tag: "oil" },
  { word: "kerosene", phonetic: "/ˈkerəsiːn/", pos: "n.", meaning: "煤油", example: "Kerosene is used as jet fuel.", exampleCn: "煤油用作航空煤油。", tag: "oil" },
  { word: "asphalt", phonetic: "/ˈæsfælt/", pos: "n.", meaning: "沥青", example: "Asphalt is the heaviest refinery product.", exampleCn: "沥青是最重的炼油产品。", tag: "oil" },
  { word: "upstream", phonetic: "/ˈʌpstriːm/", pos: "adj./n.", meaning: "上游（勘探开发）", example: "Upstream operations focus on exploration and production.", exampleCn: "上游业务聚焦勘探与生产。", tag: "oil" },
  { word: "downstream", phonetic: "/ˈdaʊnstriːm/", pos: "adj./n.", meaning: "下游（炼化销售）", example: "Downstream covers refining and marketing.", exampleCn: "下游涵盖炼化与销售。", tag: "oil" },
  { word: "midstream", phonetic: "/ˈmɪdstriːm/", pos: "adj./n.", meaning: "中游（储运）", example: "Midstream focuses on transport and storage.", exampleCn: "中游聚焦储运。", tag: "oil" },

  // ===== 储量与商务 (Reserves & Business) =====
  { word: "reserves", phonetic: "/rɪˈzɜːvz/", pos: "n.", meaning: "储量", example: "The field's proven reserves are substantial.", exampleCn: "该油田的探明储量可观。", tag: "oil" },
  { word: "proven reserves", phonetic: "/ˈpruːvn rɪˈzɜːvz/", pos: "n.", meaning: "探明储量", example: "Proven reserves have a 90% probability.", exampleCn: "探明储量有 90% 概率。", tag: "oil" },
  { word: "probable reserves", phonetic: "/ˈprɒbəbl rɪˈzɜːvz/", pos: "n.", meaning: "概算储量", example: "Probable reserves have a 50% probability.", exampleCn: "概算储量有 50% 概率。", tag: "oil" },
  { word: "possible reserves", phonetic: "/ˈpɒsəbl rɪˈzɜːvz/", pos: "n.", meaning: "可能储量", example: "Possible reserves are less certain.", exampleCn: "可能储量确定性较低。", tag: "oil" },
  { word: "OPEC", phonetic: "/ˈəʊpek/", pos: "n.", meaning: "石油输出国组织", example: "OPEC sets production targets.", exampleCn: "OPEC 设定产量目标。", tag: "oil" },
  { word: "API", phonetic: "/ˌeɪ piː ˈaɪ/", pos: "n.", meaning: "美国石油学会；API 度（油比重）", example: "API gravity indicates oil density.", exampleCn: "API 度反映原油密度。", tag: "oil" },
  { word: "barrel per day", phonetic: "/ˈbærəl pə deɪ/", pos: "n.", meaning: "桶/日（bpd）", example: "Production is 5000 barrels per day.", exampleCn: "产量为每天 5000 桶。", tag: "oil" },
  { word: "royalty", phonetic: "/ˈrɔɪəlti/", pos: "n.", meaning: "矿税；特许权使用费", example: "The royalty rate is 12.5%.", exampleCn: "矿税率为 12.5%。", tag: "oil" },
  { word: "concession", phonetic: "/kənˈseʃn/", pos: "n.", meaning: "特许权；矿权", example: "We hold a concession in the block.", exampleCn: "我们持有该区块的矿权。", tag: "oil" },
  { word: "block", phonetic: "/blɒk/", pos: "n.", meaning: "区块（勘探单元）", example: "The block covers 200 square kilometers.", exampleCn: "该区块面积 200 平方公里。", tag: "oil" },

  // ===== 测井与设备 (Logging & Equipment) =====
  { word: "logging", phonetic: "/ˈlɒɡɪŋ/", pos: "n.", meaning: "测井", example: "Well logging records formation properties.", exampleCn: "测井记录地层特性。", tag: "oil" },
  { word: "mud logging", phonetic: "/mʌd ˈlɒɡɪŋ/", pos: "n.", meaning: "泥浆录井", example: "Mud logging detects gas shows while drilling.", exampleCn: "泥浆录井在钻井中检测气显示。", tag: "oil" },
  { word: "core", phonetic: "/kɔː/", pos: "n.", meaning: "岩心", example: "A core sample shows reservoir properties.", exampleCn: "岩心样品揭示储层特性。", tag: "oil" },
  { word: "caliper log", phonetic: "/ˈkælɪpə lɒɡ/", pos: "n.", meaning: "井径测井", example: "The caliper log shows hole diameter.", exampleCn: "井径测井反映井眼直径。", tag: "oil" },
  { word: "GR log", phonetic: "/dʒiː ɑː lɒɡ/", pos: "n.", meaning: "自然伽马测井", example: "The GR log identifies shale layers.", exampleCn: "自然伽马测井识别页岩层。", tag: "oil" },
  { word: "resistivity log", phonetic: "/rɪˈzɪstɪvəti lɒɡ/", pos: "n.", meaning: "电阻率测井", example: "Resistivity logs help identify hydrocarbons.", exampleCn: "电阻率测井帮助识别油气层。", tag: "oil" },

  // ===== 安全环保 (HSE) =====
  { word: "HSE", phonetic: "/eɪtʃ es iː/", pos: "n.", meaning: "健康、安全与环境", example: "HSE is our top priority.", exampleCn: "健康安全环境是我们的首要任务。", tag: "oil" },
  { word: "H2S", phonetic: "/eɪtʃ tuː es/", pos: "n.", meaning: "硫化氢（剧毒）", example: "H2S detectors must be worn at all times.", exampleCn: "硫化氢探测器必须随时佩戴。", tag: "oil" },
  { word: "flare", phonetic: "/fleə/", pos: "n.", meaning: "火炬；放空燃烧", example: "Gas is burned at the flare stack.", exampleCn: "气体在火炬塔燃烧。", tag: "oil" },
  { word: "PPE", phonetic: "/piː piː iː/", pos: "n.", meaning: "个人防护装备", example: "Always wear proper PPE on site.", exampleCn: "现场必须穿戴个人防护装备。", tag: "oil" },
  { word: "ESD", phonetic: "/iː es diː/", pos: "n.", meaning: "紧急关断系统", example: "The ESD system can shut down the platform.", exampleCn: "紧急关断系统可关闭平台。", tag: "oil" },
  { word: "spill", phonetic: "/spɪl/", pos: "n.", meaning: "泄漏；溢油", example: "The oil spill was contained quickly.", exampleCn: "溢油被迅速控制。", tag: "oil" },
  { word: "carbon footprint", phonetic: "/ˈkɑːbən ˈfʊtprɪnt/", pos: "n.", meaning: "碳足迹", example: "We aim to reduce our carbon footprint.", exampleCn: "我们致力于减少碳足迹。", tag: "oil" },

  // ===== 日常高频交流词 =====
  { word: "schedule", phonetic: "/ˈʃedjuːl/", pos: "n./v.", meaning: "日程；安排", example: "Can we schedule a meeting for tomorrow?", exampleCn: "我们明天安排个会议好吗？", tag: "daily" },
  { word: "confirm", phonetic: "/kənˈfɜːm/", pos: "v.", meaning: "确认", example: "Please confirm your attendance by Friday.", exampleCn: "请在周五前确认是否出席。", tag: "daily" },
  { word: "available", phonetic: "/əˈveɪləbl/", pos: "adj.", meaning: "有空的；可用的", example: "Are you available this afternoon?", exampleCn: "你今天下午有空吗？", tag: "daily" },
  { word: "urgent", phonetic: "/ˈɜːdʒənt/", pos: "adj.", meaning: "紧急的", example: "This is urgent, please call me back.", exampleCn: "这事很紧急，请给我回电话。", tag: "daily" },
  { word: "deadline", phonetic: "/ˈdedlaɪn/", pos: "n.", meaning: "截止日期", example: "The deadline is next Monday.", exampleCn: "截止日期是下周一。", tag: "daily" },
  { word: "feedback", phonetic: "/ˈfiːdbæk/", pos: "n.", meaning: "反馈", example: "I'd appreciate your feedback on the report.", exampleCn: "希望你能对报告给出反馈。", tag: "daily" },
  { word: "postpone", phonetic: "/pəˈspəʊn/", pos: "v.", meaning: "推迟", example: "We have to postpone the meeting.", exampleCn: "我们不得不推迟会议。", tag: "daily" },
  { word: "appreciate", phonetic: "/əˈpriːʃieɪt/", pos: "v.", meaning: "感激；欣赏", example: "I really appreciate your help.", exampleCn: "我非常感激你的帮助。", tag: "daily" },
  { word: "recommend", phonetic: "/ˌrekəˈmend/", pos: "v.", meaning: "推荐", example: "Could you recommend a good restaurant?", exampleCn: "你能推荐一家好餐厅吗？", tag: "daily" },
  { word: "convenient", phonetic: "/kənˈviːniənt/", pos: "adj.", meaning: "方便的", example: "Is this time convenient for you?", exampleCn: "这个时间你方便吗？", tag: "daily" },
  { word: "experience", phonetic: "/ɪkˈspɪəriəns/", pos: "n./v.", meaning: "经验；经历", example: "He has ten years of field experience.", exampleCn: "他有十年现场经验。", tag: "daily" },
  { word: "equipment", phonetic: "/ɪˈkwɪpmənt/", pos: "n.", meaning: "设备；装备", example: "Check the equipment before starting.", exampleCn: "开工前检查设备。", tag: "daily" },
  { word: "safety", phonetic: "/ˈseɪfti/", pos: "n.", meaning: "安全", example: "Safety is our top priority.", exampleCn: "安全是我们的首要任务。", tag: "daily" },
  { word: "inspection", phonetic: "/ɪnˈspekʃn/", pos: "n.", meaning: "检查；巡检", example: "Routine inspection is scheduled for Monday.", exampleCn: "例行检查安排在周一。", tag: "daily" },
  { word: "maintenance", phonetic: "/ˈmeɪntənəns/", pos: "n.", meaning: "维护；保养", example: "The pump needs regular maintenance.", exampleCn: "这台泵需要定期保养。", tag: "daily" },
  { word: "supervise", phonetic: "/ˈsuːpəvaɪz/", pos: "v.", meaning: "监督；管理", example: "He supervises the field operations.", exampleCn: "他负责现场作业监督。", tag: "daily" },
  { word: "procedure", phonetic: "/prəˈsiːdʒə/", pos: "n.", meaning: "程序；流程", example: "Follow the safety procedure carefully.", exampleCn: "仔细遵守安全程序。", tag: "daily" },
  { word: "document", phonetic: "/ˈdɒkjumənt/", pos: "n./v.", meaning: "文件；记录", example: "Please document every step of the work.", exampleCn: "请记录作业的每一步。", tag: "daily" },
  { word: "report", phonetic: "/rɪˈpɔːt/", pos: "n./v.", meaning: "报告；汇报", example: "Please send me the daily report.", exampleCn: "请把日报发给我。", tag: "daily" },
  { word: "coordinate", phonetic: "/kəʊˈɔːdɪneɪt/", pos: "v.", meaning: "协调", example: "We need to coordinate with the contractor.", exampleCn: "我们需要与承包商协调。", tag: "daily" },
  { word: "estimate", phonetic: "/ˈestɪmeɪt/", pos: "n./v.", meaning: "估算；估计", example: "The cost estimate is 2 million dollars.", exampleCn: "成本估算为 200 万美元。", tag: "daily" },
  { word: "approve", phonetic: "/əˈpruːv/", pos: "v.", meaning: "批准；同意", example: "The plan was approved by management.", exampleCn: "计划已获管理层批准。", tag: "daily" },
  { word: "priority", phonetic: "/praɪˈɒrəti/", pos: "n.", meaning: "优先；优先事项", example: "Safety is our top priority.", exampleCn: "安全是首要任务。", tag: "daily" },
  { word: "conclusion", phonetic: "/kənˈkluːʒn/", pos: "n.", meaning: "结论", example: "We reached a positive conclusion.", exampleCn: "我们得出了积极的结论。", tag: "daily" },
  { word: "solution", phonetic: "/səˈluːʃn/", pos: "n.", meaning: "解决方案", example: "We proposed a technical solution.", exampleCn: "我们提出了技术方案。", tag: "daily" },

  // ===== 开车/碎片场景 =====
  { word: "commute", phonetic: "/kəˈmjuːt/", pos: "n./v.", meaning: "通勤；上下班路程", example: "My commute takes about forty minutes.", exampleCn: "我通勤大约四十分钟。", tag: "driving" },
  { word: "traffic jam", phonetic: "/ˈtræfɪk dʒæm/", pos: "n.", meaning: "交通堵塞", example: "I got stuck in a traffic jam.", exampleCn: "我堵车了。", tag: "driving" },
  { word: "navigation", phonetic: "/ˌnævɪˈɡeɪʃn/", pos: "n.", meaning: "导航", example: "Turn on the navigation to avoid traffic.", exampleCn: "打开导航避开拥堵。", tag: "driving" },
  { word: "fuel", phonetic: "/ˈfjuːəl/", pos: "n.", meaning: "燃料；燃油", example: "I need to fill up the fuel tank.", exampleCn: "我需要加油了。", tag: "driving" },
  { word: "efficiency", phonetic: "/ɪˈfɪʃnsi/", pos: "n.", meaning: "效率", example: "Practice daily to improve learning efficiency.", exampleCn: "每天练习以提高学习效率。", tag: "driving" }
];
